### PR TITLE
[BUGFIX] Fix TypoScript include

### PR DESCRIPTION
**Pull request by rschaufler**
TypoScript can not be included via `ext_localconf.php`

Using `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile` in `ext_localconf.php` has no effect what so ever and makes the extension unusable for me as is.

Tested with TYPO3 CMS `7.6.18`

### CODE REVIEW

**Comment by Scunkaneli** [comment]
Doing this does no longer work with CMS 8, as described [here](https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.5/Breaking-78384-FrontendIgnoresTCAInExtTables.html).

My pull request #17 , which is already available now for over a month, fixes the same issue, but respects the Migration rules of the Typo3 Core team. 
I suggest using exactly the request I propsed, as it's also featured by the Typo3 core team:

`In ext_tables.php neither writing directly to $GLOBALS['TCA'] and $TCA is allowed, nor writing indirectly via ExtensionManagementUtility methods. `

`ExtensionManagementUtility::addStaticFile(): A static file is registered in sys_template. Add this to Configuration/TCA/Overrides/sys_template.php`

**Comment by rschaufler** [comment]
Thanks for your feedback @Scunkaneli, i didn't check your pull request when i created mine. Does your pull request also work with TYPO3 CMS 7.6.x?

**Comment by Scunkaneli** [comment]
In #16 baden32 seems to be able to use it on CMS 7.6.18, if I'm not mistaken. Sadly I can't test it, as my only Typo3 configuration is on 8.7.1, but I can't see any reason why it should not work.

If you want, you could also try it and report back :)

**Comment by rschaufler** [comment]
I will try and gladly close this PR if it works @Scunkaneli 🤘

**Comment by Scunkaneli** [comment]
Alright I'm excited to hear back!

**Comment by rschaufler** [comment]
@Scunkaneli your pull request works just fine in TYPO3 CMS 7.6.x 🥇  will close this one now

**Pull request closed without merging**
